#!/usr/bin/env bash

set -euo pipefail
THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function help(){
cat << EOF
joefg-bot

help        : Display help text
restore     : Fetch dependencies
serve       : Spawn a bot
lint        : Run linting
type        : Run type checking
unit        : Run unit tests
EOF
}

function run_restore(){
	uv sync
	(test -f ./database/database.sqlite3 || uv run fastmigrate_create_db)
	uv run fastmigrate_run_migrations
}

function run_serve(){
	uv run fastmigrate_run_migrations
	uv run "$THISDIR/app/main.py"
}

function run_lint(){
	uv run ruff check
}

function run_type(){
	uv run mypy "$THISDIR/app"
}

function run_unit(){
	uv run pytest tests/
}

function main(){
	cmd=${1-default}
	shift || true
	case "$cmd" in
		default|help)
			help "$@"
			;;
		restore)
			run_restore
			;;
		serve)
			run_serve
			;;
		lint)
			run_lint
			;;
		type)
			run_type
			;;
		unit)
			run_unit
			;;
		*)
			echo "no-op $cmd"
			;;
	esac
}

main "$@"
